//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public int CallCenterId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CallCenter CallCenter { get; set; }
    }
}
