//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string Brand { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Color { get; set; }
        public string Collection { get; set; }
    
        public virtual Reclamation Reclamation { get; set; }
        public virtual Client Client { get; set; }
    }
}
