//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductTypes = new HashSet<ProductType>();
        }
    
        public int Id { get; set; }
        public int FurnitureFactoryId { get; set; }
        public int SellsId { get; set; }
        public string Name { get; set; }
        public System.DateTime ManufacturingDate { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public string FactoryOrigin { get; set; }
        public string Material { get; set; }
    
        public virtual FurnitureFactory FurnitureFactory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductType> ProductTypes { get; set; }
        public virtual Sells Sell { get; set; }
    }
}
