//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation
    {
        public int Id { get; set; }
        public bool Status { get; set; }
        public System.DateTime DateOfArrival { get; set; }
        public string ReclamationDescription { get; set; }
        public int ReclamationServiceId { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual ReclamationService ReclamationService { get; set; }
    }
}
